#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-docile
Version  : 1.1.5
Release  : 6
URL      : https://rubygems.org/downloads/docile-1.1.5.gem
Source0  : https://rubygems.org/downloads/docile-1.1.5.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-coveralls
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-github-markup
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-redcarpet
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-rubygems-tasks
BuildRequires : rubygem-yard

%description
# Docile
[![Gem Version](https://badge.fury.io/rb/docile.png)](http://badge.fury.io/rb/docile)
[![Build Status](https://travis-ci.org/ms-ati/docile.png)](https://travis-ci.org/ms-ati/docile)
[![Dependency Status](https://gemnasium.com/ms-ati/docile.png)](https://gemnasium.com/ms-ati/docile)
[![Code Climate](https://codeclimate.com/github/ms-ati/docile.png)](https://codeclimate.com/github/ms-ati/docile)
[![Coverage Status](https://coveralls.io/repos/ms-ati/docile/badge.png)](https://coveralls.io/r/ms-ati/docile)
[![Inline docs](http://inch-ci.org/github/ms-ati/docile.png)](http://inch-ci.org/github/ms-ati/docile)
[![Bitdeli Badge](https://d2weczhvl823v0.cloudfront.net/ms-ati/docile/trend.png)](https://bitdeli.com/free "Bitdeli Badge")

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n docile-1.1.5
gem spec %{SOURCE0} -l --ruby > rubygem-docile.gemspec

%build
gem build rubygem-docile.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
docile-1.1.5.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/docile-1.1.5
rspec -I.:lib spec/ || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/docile-1.1.5.gem
/usr/lib64/ruby/gems/2.3.0/gems/docile-1.1.5/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/docile-1.1.5/.rspec
/usr/lib64/ruby/gems/2.3.0/gems/docile-1.1.5/.ruby-gemset
/usr/lib64/ruby/gems/2.3.0/gems/docile-1.1.5/.ruby-version
/usr/lib64/ruby/gems/2.3.0/gems/docile-1.1.5/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/docile-1.1.5/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/docile-1.1.5/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/docile-1.1.5/HISTORY.md
/usr/lib64/ruby/gems/2.3.0/gems/docile-1.1.5/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/docile-1.1.5/README.md
/usr/lib64/ruby/gems/2.3.0/gems/docile-1.1.5/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/docile-1.1.5/docile.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/docile-1.1.5/lib/docile.rb
/usr/lib64/ruby/gems/2.3.0/gems/docile-1.1.5/lib/docile/chaining_fallback_context_proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/docile-1.1.5/lib/docile/execution.rb
/usr/lib64/ruby/gems/2.3.0/gems/docile-1.1.5/lib/docile/fallback_context_proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/docile-1.1.5/lib/docile/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/docile-1.1.5/on_what.rb
/usr/lib64/ruby/gems/2.3.0/gems/docile-1.1.5/spec/docile_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/docile-1.1.5/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/specifications/docile-1.1.5.gemspec
